server {
    listen 80;
    server_name _;

    # 1. Aseguramos que Nginx entienda qué es un archivo JS o CSS (Evita pantalla en blanca)
    include /etc/nginx/mime.types;
    
    # 2. Carpeta base
    root /usr/share/nginx/html;
    index index.html;

    # 3. Ruta principal del portfolio
    location /porfolio/ {
        try_files $uri $uri/ /porfolio/index.html;
    }

    # 4. Protegemos la carpeta assets de Vite para que dé 404 si no existe un archivo
    # en lugar de devolver el index.html (esto evita errores de JavaScript en consola)
    location ~ ^/porfolio/assets/ {
        try_files $uri =404;
    }

    # 5. La Raíz: Devolvemos una redirección HTML en lugar de un código 301 puro.
    # Esto "engaña" positivamente al Healthcheck de Dokploy (devuelve 200 OK), 
    # pero a la vez redirige al usuario real hacia /porfolio/
    location = / {
        default_type text/html;
        return 200 '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=/porfolio/" /></head><body>Redirigiendo...</body></html>';
    }
}