server {
    listen 80;
    server_name _;

    # Definimos la carpeta raíz donde Nginx buscará los archivos
    root /usr/share/nginx/html;

    # Configuramos el subdirectorio /porfolio
    location /porfolio/ {
        # Si el archivo existe lo muestra, si no, carga el index.html de React
        try_files $uri $uri/ /porfolio/index.html;
    }

    # (Opcional) Si entran a la raíz del dominio, redirigir al portfolio
    location = / {
        return 301 /porfolio/;
    }
}