server {
    listen 80;
    server_name _;

    # Configuración para el subdirectorio
    location /porfolio/ {
        alias /usr/share/nginx/html/porfolio/;
        index index.html;
        
        # El fallback ahora apunta al index.html dentro de /porfolio
        try_files $uri $uri/ /porfolio/index.html;
    }

    # (Opcional) Si alguien entra a la raíz de tu dominio, redirigirlo a /porfolio/
    location = / {
        return 301 /porfolio/;
    }
}